# -*- coding: utf-8 -*-
"""AI_ChatBot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1urVXivw8W7JuVj1uKeoNL1fuueqTZQDY
"""

##smart Chat bot using AI

pip install nltk

pip install newspaper3k

#import libraries

from newspaper import Article

import random
import string
import nltk
from sklearn.feature_extraction.text import CountVectorizer

from sklearn.metrics.pairwise import cosine_similarity

import numpy as np
import warnings
warnings.filterwarnings('ignore')

#Download punkt package
nltk.download('punkt', quiet=True)

#Get the Artical

article = Article('https://www.mayoclinic.org/diseases-conditions/chronic-kidney-disease/symptoms-causes/syc-20354521')

article.download()

article.parse()
article.nlp()
corpus = article.text

print(corpus)

text = corpus

# Sentence tokenization
sentence_list = nltk.sent_tokenize(text)

sentence_list

#Creating a function for random greeting to the users greeting

def greeting_res(text):
  text =  text.lower()

  # Bots responce

  Bot_greeting = ['hi', 'hello', 'hola', 'hey', 'namaste', 'namaskar']

  # User greeting
  user_greeting = ['hi', 'hello', 'hola', 'hey', 'namaste', 'namaskar']

  for word in text.split():
    if word in user_greeting:
      return random.choice(Bot_greeting)

def index_sort (list_var):
  lenght = len(list_var)
  list_index = list(range(0, lenght))

  x = list_var

  for i in range(lenght):
    for j in range((lenght)):
      if x[list_index[i]] > x[list_index[j]]:
        #swap

        temp = list_index[i]
        list_index[i] = list_index[j]
        list_index[j] = temp

  return list_index

# Create the bots response
def bot_response (user_input):
  user_input = user_input.lower()
  sentence_list.append(user_input)
  bot_response = ' '

  cm = CountVectorizer().fit_transform(sentence_list)

  similarity_score = cosine_similarity(cm[-1], cm)

  similarity_score_list = similarity_score.flatten()

  index = index_sort(similarity_score_list)

  index  = index[1:]
  response_flag = 0

  j = 0
  for i in range(len(index)):
    if similarity_score_list[index[i]] >0.0:
      bot_response = bot_response + ' ' +sentence_list[index[i]]
      response_flag = 1
      j = j+1
    if j > 2:
      break
    
  if response_flag  == 0:
    bot_response = bot_response+ ' ' + ' I apologize I dont understand.'

  sentence_list.remove(user_input) 

  return bot_response

# Start the chat 

print(" I am AI Doc bot : Ask me your question ")


exit_list = ['exit', 'bye', 'quit']

while (True):
  user_input = input()
  if user_input.lower() in exit_list:
    print('AI Doc: Chat with you later !! Take care')
    break
  else:
    if greeting_res (user_input) != None:
      print('AI Doc Bot: '+ greeting_res(user_input))
    else:
      print('AI Doc :' + bot_response(user_input))





